#!/bin/bash
NAME="udplogger"
ETCDIR="/etc"
OPTDIR="/opt"
OPTLOC="$OPTDIR/$NAME"
SERVICEDIR="$ETCDIR/systemd/system"
SERVICESCRIPT="$NAME.service"

if [ -f "$SERVICEDIR/$SERVICESCRIPT" ]; then
    echo "Uninstalling service $NAME"
    systemctl stop "$SERVICESCRIPT"
    systemctl disable "$SERVICESCRIPT"
fi

py3clean "$OPTLOC"

#echo "Removing files"
#if [ -d "$OPTLOC" ]; then
#    rm -rf "$OPTLOC"
#fi

exit 0
