#!/bin/bash
NAME="udplogger"
ETCDIR="/etc"
OPTDIR="/opt"
OPTLOC="$OPTDIR/$NAME"
SERVICEDIR="$ETCDIR/systemd/system"
SERVICESCRIPT="$NAME.service"
PIP_INSTALL="$OPTLOC/pip_install.sh"

py3clean "$OPTLOC"

if [ -f "$PIP_INSTALL" ]; then
    $PIP_INSTALL
fi

echo "Install automatic startup service for $NAME"
if [ -f "$SERVICEDIR/$SERVICESCRIPT" ]; then
    systemctl enable $SERVICESCRIPT
    systemctl start $SERVICESCRIPT
fi

exit 0
